apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ulttodo
  name: ulttodo-service
spec:
  ports:
  - name: 5678-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app.kubernetes.io/name: ulttodo
  type: NodePort
